### ISSUE TITLE
Data yang anda masukan tidak sesuai!

### ISSUE THREAD

**Issue by mrtakt** [pilarxyz/cek-rekening#1]
Format Aslinya Seperti Apa? Nomor Menggunakan +62,62 atau 0 
saya sudah coba tidak bisa apakah karena ip? 
saya direct ke https://cek-rekening.lfourr.com/checkAccount tidak dapat akses

mohon bantuannya :)

https://api-rekening.lfourr.com/getEwalletAccount?bankCode=dana&accountNumber=

![Screenshot (250)](https://github.com/pilarxyz/cek-rekening/assets/88103824/78966e11-0031-47d4-b73f-b194731eb2d2)

**Comment by pilarxyz** [comment]
Menggunakan 0

dari url yang anda kirim, anda salah memasukan bankCode, yang seharusnya di tulis menggunakan huruf capital

<img width="555" alt="Screenshot 2023-12-13 at 11 44 59" src="https://github.com/pilarxyz/cek-rekening/assets/84503940/c5c72095-1277-4da6-87fc-ff7dd6b60df1">
