### ISSUE TITLE
Untuk virtual Account apakah bisa?

### ISSUE THREAD

**Issue by masbudikusuma** [pilarxyz/cek-rekening#4]
Mantaps kak, sudah dicoba.
ijin tanya, untuk Virtual Account sepertinya masih belum bisa ya?

**Comment by pilarxyz** [comment]
untuk VA tidak bisa, hanya nomor rekening saja

**Comment by pilarxyz** [comment]
untuk VA tidak bisa, hanya nomor rekening saja
